### ISSUE TITLE
Setting soc-min/max with number.set_value

### ISSUE THREAD

**Issue by ato-dev-80** [zbigniewmotyka/home-assistant-solplanet#45]
Hi, not sure if this is an issue with the integration or my understanding is incorrect.
From my perspective it should be possible to set the NumberEntity of soc_min from an automation:

```yaml
automation:  
  - alias: Switch on PV Excess Charging 1P
    description: ""
    triggers:
      - trigger: state
        entity_id: sensor.pv_excess_charging_button
        to: "on"
    condition: []
    actions:
      - action: number.set_value
        target:
          entity_id: number.solplanet_battery_<myinverter_id>_soc_min
        data:
          value: 100
    mode: single
```

However, this does not seem to work (do not get any errors though). Setting the value manually through the predefined input-fields seems to work properly. 

Any idea what could be wrong here?
